### ISSUE TITLE
Ensure versions of QA packages in requirements are up to date with those in pre-commit config

### ISSUE THREAD

**Issue by cortadocodes** [octue/octue-sdk-python#267]
The versions of e.g. `flake8`, `black` should be aligned between `pre-commit-config.yaml` and `requirements-dev.txt`.

**Comment by thclark** [comment]
@cortadocodes can you expand on this with a description and labels so I can triage it please?

**Comment by cortadocodes** [comment]
I'm wondering whether we need these packages in `requirements-dev.txt` as well as in the pre-commit config? I never run them myself anymore as `pre-commit` takes care of it for me.

**Comment by thclark** [comment]
The answer to this is that yes, they should be present (in the devtools section of pyproject.toml). The reason is that most developers would have some or all of these tools set up to run on save (I certainly do) and having different versions of the tools installed in your dev environment compared to the pre-commit environment creates oscillations (e.g. continually flip-flopping a code reformat).
