### ISSUE TITLE
Consider turning on code scanning for repository

### ISSUE THREAD

**Issue by cortadocodes** [octue/octue-sdk-python#526]

**Comment by thclark** [comment]
Up to you @cortadocodes - I turned it off because:
- It creates a lot of noise being mostly issues with the devtools rather than us
- The PRs produced don't meet our process specs so all I ever do is close them and bump the dependency myself
- We maintain pretty wide dependency ranges anyway, allowing end-applications to pin their final sets of dependencies and resolve vulnerabilities that way.
- We pretty regularly maintain the lib dependencies anyhow.

I guess it couldn't hurt, but entirely up to you since it'll be you who has to sort through the noise :)
